# Generated by Django 5.1 on 2024-08-12 13:07

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogsite", "0002_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
